######################################################################
##
## Filename: and_clk.udo
## Created on: Wed Aug 17 08:01:31 Sri Lanka Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
